import type { CatalogItem } from "./types";

// Slice 1 정적 카탈로그 — 3개 항목으로 E2E를 관통한다 (spec §5.2).
// 이후 슬라이스에서 C-03~C-09, U-01~U-67, W-01~W-27로 확장된다.
export const CATALOG: CatalogItem[] = [
  {
    id: "C-01",
    category: "container_hardening",
    title: "root(UID 0) 실행",
    severity: "High",
    method: "D+R",
    failCriterion: "USER 미지정 or 실행 UID=0",
  },
  {
    id: "C-02",
    category: "container_hardening",
    title: "하드코딩 시크릿",
    severity: "Critical",
    method: "D",
    failCriterion: "ENV/ARG에 password·token·key 패턴",
  },
  {
    id: "C-03",
    category: "container_hardening",
    title: "불필요한 노출 포트",
    severity: "Medium",
    method: "D+R",
    failCriterion: "관리·DB 포트(22, 3306 등) EXPOSE/LISTEN",
  },
  {
    id: "C-04",
    category: "container_hardening",
    title: "base 이미지 태그 미고정",
    severity: "Medium",
    method: "D",
    failCriterion: ":latest 또는 태그 없음",
  },
  {
    id: "C-05",
    category: "container_hardening",
    title: "위험 패키지 잔존",
    severity: "Medium",
    method: "R",
    failCriterion: "curl/wget/gcc/apt 등 빌드·네트워크 도구 상주",
  },
  {
    id: "C-06",
    category: "container_hardening",
    title: "setuid/setgid 바이너리",
    severity: "High",
    method: "R",
    failCriterion: "예상 외 setuid/setgid 바이너리 존재",
  },
  {
    id: "C-07",
    category: "container_hardening",
    title: "쓰기 가능 루트 FS",
    severity: "Medium",
    method: "R",
    failCriterion: "--read-only 미적용 시 루트 FS 쓰기 가능",
  },
  {
    id: "C-08",
    category: "container_hardening",
    title: "HEALTHCHECK 부재",
    severity: "Low",
    method: "D",
    failCriterion: "HEALTHCHECK 지시어 없음",
  },
  {
    id: "C-09",
    category: "container_hardening",
    title: "ADD 원격 사용",
    severity: "Low",
    method: "D",
    failCriterion: "COPY 대신 원격 URL ADD 사용",
  },
  // Slice 3 — 계정/파일권한 축 (KISA U 항목 중 최소 컨테이너에서 관찰 가능한 것 우선)
  {
    id: "U-04",
    category: "unix",
    title: "비밀번호 파일 보호",
    severity: "High",
    method: "R",
    failCriterion: "/etc/passwd 암호 필드에 shadow(x) 대신 실제 해시 노출",
  },
  {
    id: "U-05",
    category: "unix",
    title: "root 이외의 UID가 '0' 금지",
    severity: "High",
    method: "R",
    failCriterion: "root 외 계정의 UID가 0",
  },
  {
    id: "U-16",
    category: "unix",
    title: "/etc/passwd 파일 소유자 및 권한 설정",
    severity: "High",
    method: "R",
    failCriterion: "소유자 root 아님 또는 권한이 644 초과",
  },
  {
    id: "U-18",
    category: "unix",
    title: "/etc/shadow 파일 소유자 및 권한 설정",
    severity: "High",
    method: "R",
    failCriterion: "소유자 root 아님 또는 그룹 쓰기·기타(others) 권한 존재",
  },
  {
    id: "U-19",
    category: "unix",
    title: "/etc/hosts 파일 소유자 및 권한 설정",
    severity: "High",
    method: "R",
    failCriterion: "소유자 root 아님 또는 권한이 644 초과",
  },
  {
    id: "U-22",
    category: "unix",
    title: "/etc/services 파일 소유자 및 권한 설정",
    severity: "High",
    method: "R",
    failCriterion: "소유자 root 아님 또는 권한이 644 초과",
  },
  {
    id: "U-25",
    category: "unix",
    title: "world writable 파일 점검",
    severity: "High",
    method: "R",
    failCriterion: "others 쓰기 권한(world-writable) 파일 존재",
  },
  // Slice 4 — 웹 서비스 축 (KISA W 항목을 nginx 설정에 매핑; nginx 미탐지 시 skip)
  {
    id: "W-01",
    category: "web",
    title: "디렉토리 리스팅 제거",
    severity: "High",
    method: "R",
    failCriterion: "nginx autoindex on 설정 존재",
  },
  {
    id: "W-08",
    category: "web",
    title: "웹서비스 로그 설정",
    severity: "High",
    method: "R",
    failCriterion: "access_log 미설정 또는 off",
  },
  {
    id: "W-09",
    category: "web",
    title: "웹서버 에러 메시지 통제",
    severity: "High",
    method: "R",
    failCriterion: "custom error_page 미설정 (기본 에러페이지가 서버 정보 노출)",
  },
  {
    id: "W-21",
    category: "web",
    title: "웹서버 서비스 데몬 실행 권한 제한",
    severity: "High",
    method: "R",
    failCriterion: "nginx user 지시어가 root",
  },
  {
    id: "W-22",
    category: "web",
    title: "웹 서비스 환경설정 파일 보호",
    severity: "High",
    method: "R",
    failCriterion: "nginx.conf 소유자 root 아님 또는 그룹/기타 쓰기 권한",
  },
  {
    id: "W-25",
    category: "web",
    title: "불필요한 HTTP Method 제한",
    severity: "High",
    method: "R",
    failCriterion: "dav_methods로 PUT/DELETE 등 위험 메서드 허용",
  },
  {
    id: "W-26",
    category: "web",
    title: "웹서비스 헤더 정보 노출 제한",
    severity: "High",
    method: "R",
    failCriterion: "server_tokens off 미설정 (버전 정보 노출)",
  },
];

export function getCatalogItem(id: string): CatalogItem {
  const item = CATALOG.find((c) => c.id === id);
  if (!item) throw new Error(`Unknown catalog id: ${id}`);
  return item;
}
